In [2]:
from sklearn.model_selection import KFold
import numpy as np

In [55]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=3)
kf.get_n_splits(X)

3

In [56]:
[print(i, j) for i, j in kf.split(X)]

[2 3] [0 1]
[0 1 3] [2]
[0 1 2] [3]


[None, None, None]

In [59]:
a, b, c = kf.split(X)
print(a)
print()
print(b)
print()
print(c)

(array([2, 3]), array([0, 1]))

(array([0, 1, 3]), array([2]))

(array([0, 1, 2]), array([3]))


In [65]:
print(X)
print(y)
print()

for i in range(1):
    for train_index, test_index in kf.split(X):
        print("TRAIN:", train_index, "TEST:", test_index)

        X_train, X_test = X[train_index], X[test_index]
        print(X_train)
        print(X_test)

        y_train, y_test = y[train_index], y[test_index]
        print(y_train)
        print(y_test)

        print()

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4]

TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]]
[3 4]
[1 2]

TRAIN: [0 1 3] TEST: [2]
[[1 2]
 [3 4]
 [7 8]]
[[5 6]]
[1 2 4]
[3]

TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [5 6]]
[[7 8]]
[1 2 3]
[4]



In [63]:
min([i for i in range(6)], key=lambda n: (n-6)**2)

5

In [73]:
d = dict()

for n in range(10):

    try:
        d[n] = list()
        
        for i in range(5):
            d[n].append(n+i)

    except Exception as e:
        pass

In [80]:
[(item[0], item[1], np.mean(item[1])) for item in d.items()]

[(0, [0, 1, 2, 3, 4], 2.0),
 (1, [1, 2, 3, 4, 5], 3.0),
 (2, [2, 3, 4, 5, 6], 4.0),
 (3, [3, 4, 5, 6, 7], 5.0),
 (4, [4, 5, 6, 7, 8], 6.0),
 (5, [5, 6, 7, 8, 9], 7.0),
 (6, [6, 7, 8, 9, 10], 8.0),
 (7, [7, 8, 9, 10, 11], 9.0),
 (8, [8, 9, 10, 11, 12], 10.0),
 (9, [9, 10, 11, 12, 13], 11.0)]

In [88]:
min(d.items(), key=lambda x: (np.mean(x[1])-0)**2 )[0]

0